# Generated by Django 4.2.1 on 2024-03-26 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopmain', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['title', '-price'], 'verbose_name': 'Продукты', 'verbose_name_plural': 'Продукты'},
        ),
    ]
